#if !canImport(ObjectiveC)
import XCTest

extension AttributeParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AttributeParserTests = [
        ("testDictionary", testDictionary),
        ("testParseBool", testParseBool),
        ("testParseFloat", testParseFloat),
        ("testParseFloats", testParseFloats),
        ("testParseLength", testParseLength),
        ("testParsePoints", testParsePoints),
        ("testParserOrder", testParserOrder),
        ("testParseString", testParseString),
        ("testParseURL", testParseURL),
        ("testParseURLSelector", testParseURLSelector),
    ]
}

extension CGPathSegmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CGPathSegmentTests = [
        ("testSegments", testSegments),
        ("testString", testString),
    ]
}

extension CGRendererTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CGRendererTests = [
        ("testAlphaClips", testAlphaClips),
        ("testDrawsRect", testDrawsRect),
    ]
}

extension CommandLineArgumentsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandLineArgumentsTests = [
        ("testParseModifiers", testParseModifiers),
        ("testParseModifiersThrowsForDuplicateModifiers", testParseModifiersThrowsForDuplicateModifiers),
        ("testParseModifiersThrowsForMissingPrefix", testParseModifiersThrowsForMissingPrefix),
        ("testParseModifiersThrowsForOddPairs", testParseModifiersThrowsForOddPairs),
        ("testParseModifiersThrowsForUnknownModifiers", testParseModifiersThrowsForUnknownModifiers),
    ]
}

extension CommandLineConfigurationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandLineConfigurationTests = [
        ("testNewURLForFormat", testNewURLForFormat),
        ("testParseConfiguration", testParseConfiguration),
        ("testParseConfigurationThrows", testParseConfigurationThrows),
        ("testParseFileURL", testParseFileURL),
    ]
}

extension CoordinateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoordinateTests = [
        ("testDelimeterComma", testDelimeterComma),
        ("testDelimeterSpace", testDelimeterSpace),
        ("testPrecisionCapped", testPrecisionCapped),
        ("testPrecisionMax", testPrecisionMax),
    ]
}

extension DOMElementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DOMElementTests = [
        ("testCircle", testCircle),
        ("testEllipse", testEllipse),
        ("testGroup", testGroup),
        ("testLine", testLine),
        ("testPolygon", testPolygon),
        ("testPolyline", testPolyline),
        ("testRect", testRect),
        ("testText", testText),
    ]
}

extension GradientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GradientTests = [
        ("testLinerGradient", testLinerGradient),
        ("testLinerGradientStop", testLinerGradientStop),
    ]
}

extension ImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageTests = [
        ("testImageRasterizeAndScales", testImageRasterizeAndScales),
        ("testImageRasterizes", testImageRasterizes),
        ("testInvalidSVGReturnsNil", testInvalidSVGReturnsNil),
        ("testMissingSVGReturnsNil", testMissingSVGReturnsNil),
    ]
}

extension LayerTreeBuilderLayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreeBuilderLayerTests = [
        ("testMakeImageContentsFromDOM", testMakeImageContentsFromDOM),
        ("testMakeTextContentsFromDOM", testMakeTextContentsFromDOM),
        ("testMakeUseContentsFromDOM", testMakeUseContentsFromDOM),
        ("testMakeUseContentsThrows", testMakeUseContentsThrows),
    ]
}

extension LayerTreeBuilderShapeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreeBuilderShapeTests = [
        ("testDOMRectMakesRect", testDOMRectMakesRect),
        ("testDOMRectMakesRectWithDefaultOrigin", testDOMRectMakesRectWithDefaultOrigin),
    ]
}

extension LayerTreeBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreeBuilderTests = [
        ("testDOMClipMakesShape", testDOMClipMakesShape),
        ("testDOMGroupMakesChildContents", testDOMGroupMakesChildContents),
        ("testDOMMaskMakesLayer", testDOMMaskMakesLayer),
        ("testDOMPatternMakesPattern", testDOMPatternMakesPattern),
        ("testMakeViewBoxTransform", testMakeViewBoxTransform),
        ("testStrokeAttributes", testStrokeAttributes),
    ]
}

extension LayerTreeColorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreeColorTests = [
        ("testFromDOM", testFromDOM),
        ("testLuminanceConverter", testLuminanceConverter),
        ("testMultiplyingAlpha", testMultiplyingAlpha),
        ("testRGBi", testRGBi),
        ("testStaticColors", testStaticColors),
        ("testWithAlpha", testWithAlpha),
    ]
}

extension LayerTreeCommandGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreeCommandGeneratorTests = [
        ("testClip", testClip),
        ("testTransforms", testTransforms),
    ]
}

extension LayerTreeImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreeImageTests = [
        ("testImageEquality", testImageEquality),
        ("testInit", testInit),
    ]
}

extension LayerTreeLayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreeLayerTests = [
        ("testContentsTextEquality", testContentsTextEquality),
        ("testLayersWithComplexContentsAreAppendedWithoutLayer", testLayersWithComplexContentsAreAppendedWithoutLayer),
        ("testLayersWithSimpleContentsAreAppendedWithoutLayer", testLayersWithSimpleContentsAreAppendedWithoutLayer),
    ]
}

extension LayerTreePathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreePathTests = [
        ("testClose", testClose),
        ("testCubic", testCubic),
        ("testCubicSmoothAbsolute", testCubicSmoothAbsolute),
        ("testCubicSmoothRelative", testCubicSmoothRelative),
        ("testDOMCubicSmooth", testDOMCubicSmooth),
        ("testDOMQuadraticSmooth", testDOMQuadraticSmooth),
        ("testHorizontal", testHorizontal),
        ("testLine", testLine),
        ("testLocation", testLocation),
        ("testMove", testMove),
        ("testQuadraticBalanced", testQuadraticBalanced),
        ("testQuadraticSmoothAbsolute", testQuadraticSmoothAbsolute),
        ("testQuadraticUnbalanced", testQuadraticUnbalanced),
        ("testVertical", testVertical),
    ]
}

extension LayerTreeShapeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreeShapeTests = [
        ("testCircleBuilder", testCircleBuilder),
        ("testEllipseBuilder", testEllipseBuilder),
        ("testLineBuilder", testLineBuilder),
        ("testPathBuilder", testPathBuilder),
        ("testPolygonBuilder", testPolygonBuilder),
        ("testPolylineBuilder", testPolylineBuilder),
        ("testRectBuilder", testRectBuilder),
        ("testShapeEquality", testShapeEquality),
    ]
}

extension LayerTreeTransformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayerTreeTransformTests = [
        ("testDOMMakesLayerTreeTranslate", testDOMMakesLayerTreeTranslate),
        ("testDOMMakesMatrixTransform", testDOMMakesMatrixTransform),
        ("testDOMMakesMultipleTransforms", testDOMMakesMultipleTransforms),
        ("testDOMMakesRotatePointTransform", testDOMMakesRotatePointTransform),
        ("testDOMMakesRotateTransform", testDOMMakesRotateTransform),
        ("testDOMMakesScaleTransform", testDOMMakesScaleTransform),
        ("testDOMMakesSkewXTransform", testDOMMakesSkewXTransform),
        ("testDOMMakesSkewYTransform", testDOMMakesSkewYTransform),
        ("testMatrixConcatenation", testMatrixConcatenation),
        ("testRotateMatrix", testRotateMatrix),
        ("testScaleMatrix", testScaleMatrix),
        ("testSkewXMatrix", testSkewXMatrix),
        ("testSkewYMatrix", testSkewYMatrix),
        ("testTranslateMatrix", testTranslateMatrix),
    ]
}

extension ParserColorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserColorTests = [
        ("testColorHex", testColorHex),
        ("testColorKeyword", testColorKeyword),
        ("testColorNone", testColorNone),
        ("testColorRGBf", testColorRGBf),
        ("testColorRGBi", testColorRGBi),
    ]
}

extension ParserGraphicAttributeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserGraphicAttributeTests = [
        ("testCircle", testCircle),
        ("testDisplayMode", testDisplayMode),
        ("testPresentationAttributes", testPresentationAttributes),
        ("testStrokeLineCap", testStrokeLineCap),
        ("testStrokeLineJoin", testStrokeLineJoin),
    ]
}

extension ParserTransformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTransformTests = [
        ("testMatrix", testMatrix),
        ("testRotate", testRotate),
        ("testRotatePoint", testRotatePoint),
        ("testScale", testScale),
        ("testSkewX", testSkewX),
        ("testSkewY", testSkewY),
        ("testTransform", testTransform),
        ("testTranslate", testTranslate),
    ]
}

extension ParserXMLGradientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserXMLGradientTests = [
        ("testParseGradients", testParseGradients),
    ]
}

extension ParserXMLImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserXMLImageTests = [
        ("testImage", testImage),
        ("testImageLineBreaks", testImageLineBreaks),
    ]
}

extension ParserXMLPathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserXMLPathTests = [
        ("testArc", testArc),
        ("testClose", testClose),
        ("testCubic", testCubic),
        ("testCubicSmooth", testCubicSmooth),
        ("testEquality", testEquality),
        ("testHorizontal", testHorizontal),
        ("testLine", testLine),
        ("testMove", testMove),
        ("testPath", testPath),
        ("testPathLineBreak", testPathLineBreak),
        ("testPathLong", testPathLong),
        ("testQuadratic", testQuadratic),
        ("testQuadraticSmooth", testQuadraticSmooth),
        ("testScanBool", testScanBool),
        ("testScanCoordinate", testScanCoordinate),
        ("testVerical", testVerical),
    ]
}

extension ParserXMLPatternTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserXMLPatternTests = [
        ("testPattern", testPattern),
        ("testPatternContentUnits", testPatternContentUnits),
        ("testPatternUnits", testPatternUnits),
    ]
}

extension ParserXMLTextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserXMLTextTests = [
        ("testEmptyTextNodeReturnsNil", testEmptyTextNodeReturnsNil),
        ("testParseText", testParseText),
        ("testTextNodeParses", testTextNodeParses),
    ]
}

extension RendererCoreGraphicsTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RendererCoreGraphicsTypesTests = [
        ("testBlendMode", testBlendMode),
        ("testColor", testColor),
        ("testFillRule", testFillRule),
        ("testFloat", testFloat),
        ("testLineCap", testLineCap),
        ("testLineJoin", testLineJoin),
        ("testPoint", testPoint),
        ("testRect", testRect),
        ("testShapeEllipse", testShapeEllipse),
        ("testShapeLine", testShapeLine),
        ("testShapePath", testShapePath),
        ("testShapePolygon", testShapePolygon),
        ("testShapeRect", testShapeRect),
        ("testSize", testSize),
        ("testSubpath", testSubpath),
        ("testTextPath", testTextPath),
        ("testTransform", testTransform),
    ]
}

extension RendererLayerTreeProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RendererLayerTreeProviderTests = [
        ("testBlendMode", testBlendMode),
        ("testColor", testColor),
        ("testFillRule", testFillRule),
        ("testFloat", testFloat),
        ("testImage", testImage),
        ("testLineCap", testLineCap),
        ("testLineJoin", testLineJoin),
        ("testPoint", testPoint),
        ("testRect", testRect),
        ("testShape", testShape),
        ("testSize", testSize),
        ("testSubPaths", testSubPaths),
        ("testTextPathIsUnsupported", testTextPathIsUnsupported),
        ("testTransform", testTransform),
    ]
}

extension RendererTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RendererTests = [
        ("testPerformCommands", testPerformCommands),
    ]
}

extension SAXParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SAXParserTests = [
        ("testInvalidXMLThrows", testInvalidXMLThrows),
        ("testMissingFileThrows", testMissingFileThrows),
        ("testUnexpectedElementsThrows", testUnexpectedElementsThrows),
        ("testUnexpectedNamespaceElementsSkipped", testUnexpectedNamespaceElementsSkipped),
        ("testValidSVGParses", testValidSVGParses),
    ]
}

extension SVGTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SVGTests = [
        ("testClipPath", testClipPath),
        ("testParseDefs", testParseDefs),
        ("testParseSVGInvalidNode", testParseSVGInvalidNode),
        ("testParseSVGMissingHeightInvalidNode", testParseSVGMissingHeightInvalidNode),
        ("testParseSVGMissingWidthInvalidNode", testParseSVGMissingWidthInvalidNode),
        ("testSVG", testSVG),
        ("testViewBox", testViewBox),
    ]
}

extension ScannerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScannerTests = [
        ("testIsEOF", testIsEOF),
        ("testScanBool", testScanBool),
        ("testScanCase", testScanCase),
        ("testScanCharacter", testScanCharacter),
        ("testScanCharsetEmoji", testScanCharsetEmoji),
        ("testScanCharsetHex", testScanCharsetHex),
        ("testScanCoordinate", testScanCoordinate),
        ("testScanDouble", testScanDouble),
        ("testScanFloat", testScanFloat),
        ("testScanLength", testScanLength),
        ("testScanPercentage", testScanPercentage),
        ("testScanPercentageFloat", testScanPercentageFloat),
        ("testScanString", testScanString),
        ("testScanUInt8", testScanUInt8),
    ]
}

extension StackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StackTests = [
        ("testInit", testInit),
        ("testMutation", testMutation),
        ("testPop", testPop),
        ("testPush", testPush),
    ]
}

extension StyleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StyleTests = [
        ("testStyle", testStyle),
        ("testStyles", testStyles),
    ]
}

extension URLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLTests = [
        ("testDataURL", testDataURL),
        ("testDecodedData", testDecodedData),
        ("testDecodedDataLineBreak", testDecodedDataLineBreak),
    ]
}

extension UseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UseTests = [
        ("testUse", testUse),
    ]
}

extension ValueParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValueParserTests = [
        ("testBool", testBool),
        ("testCoordinate", testCoordinate),
        ("testFill", testFill),
        ("testFloat", testFloat),
        ("testFloats", testFloats),
        ("testLength", testLength),
        ("testPercentage", testPercentage),
        ("testPoints", testPoints),
        ("testRaw", testRaw),
        ("testUrl", testUrl),
        ("testUrlSelector", testUrlSelector),
    ]
}

extension XMLParserElementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLParserElementTests = [
        ("testCircle", testCircle),
        ("testElementParserErrorsPreserveLineNumbers", testElementParserErrorsPreserveLineNumbers),
        ("testElementParserErrorsPreserveLineNumbersFromElement", testElementParserErrorsPreserveLineNumbersFromElement),
        ("testElementParserSkipsErrors", testElementParserSkipsErrors),
        ("testEllipse", testEllipse),
        ("testLine", testLine),
        ("testPolygon", testPolygon),
        ("testPolygonFillRule", testPolygonFillRule),
        ("testPolyline", testPolyline),
        ("testRect", testRect),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AttributeParserTests.__allTests__AttributeParserTests),
        testCase(CGPathSegmentTests.__allTests__CGPathSegmentTests),
        testCase(CGRendererTests.__allTests__CGRendererTests),
        testCase(CommandLineArgumentsTests.__allTests__CommandLineArgumentsTests),
        testCase(CommandLineConfigurationTests.__allTests__CommandLineConfigurationTests),
        testCase(CoordinateTests.__allTests__CoordinateTests),
        testCase(DOMElementTests.__allTests__DOMElementTests),
        testCase(GradientTests.__allTests__GradientTests),
        testCase(ImageTests.__allTests__ImageTests),
        testCase(LayerTreeBuilderLayerTests.__allTests__LayerTreeBuilderLayerTests),
        testCase(LayerTreeBuilderShapeTests.__allTests__LayerTreeBuilderShapeTests),
        testCase(LayerTreeBuilderTests.__allTests__LayerTreeBuilderTests),
        testCase(LayerTreeColorTests.__allTests__LayerTreeColorTests),
        testCase(LayerTreeCommandGeneratorTests.__allTests__LayerTreeCommandGeneratorTests),
        testCase(LayerTreeImageTests.__allTests__LayerTreeImageTests),
        testCase(LayerTreeLayerTests.__allTests__LayerTreeLayerTests),
        testCase(LayerTreePathTests.__allTests__LayerTreePathTests),
        testCase(LayerTreeShapeTests.__allTests__LayerTreeShapeTests),
        testCase(LayerTreeTransformTests.__allTests__LayerTreeTransformTests),
        testCase(ParserColorTests.__allTests__ParserColorTests),
        testCase(ParserGraphicAttributeTests.__allTests__ParserGraphicAttributeTests),
        testCase(ParserTransformTests.__allTests__ParserTransformTests),
        testCase(ParserXMLGradientTests.__allTests__ParserXMLGradientTests),
        testCase(ParserXMLImageTests.__allTests__ParserXMLImageTests),
        testCase(ParserXMLPathTests.__allTests__ParserXMLPathTests),
        testCase(ParserXMLPatternTests.__allTests__ParserXMLPatternTests),
        testCase(ParserXMLTextTests.__allTests__ParserXMLTextTests),
        testCase(RendererCoreGraphicsTypesTests.__allTests__RendererCoreGraphicsTypesTests),
        testCase(RendererLayerTreeProviderTests.__allTests__RendererLayerTreeProviderTests),
        testCase(RendererTests.__allTests__RendererTests),
        testCase(SAXParserTests.__allTests__SAXParserTests),
        testCase(SVGTests.__allTests__SVGTests),
        testCase(ScannerTests.__allTests__ScannerTests),
        testCase(StackTests.__allTests__StackTests),
        testCase(StyleTests.__allTests__StyleTests),
        testCase(URLTests.__allTests__URLTests),
        testCase(UseTests.__allTests__UseTests),
        testCase(ValueParserTests.__allTests__ValueParserTests),
        testCase(XMLParserElementTests.__allTests__XMLParserElementTests),
    ]
}
#endif
